package lk.ijse.gdse.controller.util;

public enum Routes {
    CREATE_ACCOUNT,APPROVE_lOANS,DEPOSIT,INTER_ACCOUNT_TRANSACTION,LOAN_INSTALLMENT,MAIN_DASHBOARD,REJECTED_LOANS,REQUEST_LOANS,WITHDRAWAL,
    REPORT_DASHBOARD, VIEW_ACCOUNT,VIEW_DAILY_TRANSACTIONS,VIEW_DEPOSITS,VIEW_LOAN_INSTALLMENTS,VIEW_WITHDRAWALS,LOGIN,
    VIEW_APPROVED_LOANS,VIEW_PENDING_LOANS,VIEW_SETTLED_LOANS,LOAN_TYPES_DASHBOARD;
}
